site_name: Connect Four Lab Documentation
# theme: default
# theme_dir: theme
docs_dir: sources

pages:
- Home: index.md
- Game:
  - Game: Game/game.md
  - Timer: Game/timer.md
  - Helpers: Game/helpers.md
- Agents:
  - Base class: Agents/base.md
  - Trainers: Agents/trainers.md
  - List of Agents: Agents/agents.md
  - List of Strategies: Agents/strategies.md
